[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund"

[context.production.environment]
  NODE_ENV = "production"
  VITE_APP_URL = "https://familycentral.io"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  VITE_APP_URL = "https://jocular-quokka-b1e951.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[functions]
  directory = "netlify/functions"

[forms]
  [forms.contact]
    name = "contact"